#!/bin/sh

choice=$(dmenu-mac_path | dmenu-mac -i "$@")
status=$?

[ "$status" -eq 0 ] || exit "$status"
[ -n "$choice" ] || exit 1

case "$choice" in
*.app)
  exec open "$choice"
  ;;
*)
  exec "$choice"
  ;;
esac
